#!/usr/bin/env node
// Engineering Knowledge Engine v1 regression coverage: every deterministic derivation produces the
// expected, reproducible result against a hand-crafted repository-analysis.json fixture (this engine's
// only contract is that JSON shape, so tests are decoupled from Repository Intelligence's own internals),
// plus one true end-to-end run proving the real single-command chain (Repository Intelligence ->
// Engineering Knowledge) actually works together.
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");

const repoRoot = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(repoRoot, "scripts/engineering-knowledge.js"), "utf8");
const repoIntelSource = fs.readFileSync(path.join(repoRoot, "scripts/repository-intelligence.js"), "utf8");

function writeFile(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function writeJson(file, value) {
  writeFile(file, `${JSON.stringify(value, null, 2)}\n`);
}

// A small, precisely hand-crafted repository-analysis.json -- not generated by Repository Intelligence --
// exercising: a Full-stack strongly-detected module with a debt-overlapping file, a Backend-only weakly-
// detected module whose own model file shares its name (self-dependency exclusion case), and one entirely
// undetected module.
const ANALYSIS_FIXTURE = {
  projectName: "Fixture Project",
  frameworks: ["React", "Express", "Mongoose (MongoDB ODM)", "Tailwind CSS"],
  technicalDebtIndicators: [
    { indicator: "TODO/FIXME/HACK/XXX markers in source", count: 1, files: ["backend/controllers/userController.js"] },
  ],
  detectedModules: [
    {
      name: "Authentication",
      detected: true,
      confidence: "strong",
      evidence: ["backend/routes/authRoutes.js", "backend/models/User.js", "frontend/src/pages/Login.js", "backend/controllers/userController.js"],
    },
    {
      name: "Attendance",
      detected: true,
      confidence: "weak",
      evidence: ["backend/models/Attendance.js"],
    },
    { name: "Admin", detected: false, confidence: "none", evidence: [] },
  ],
  timestamp: "2026-01-01T00:00:00.000Z",
};

function makeFixture(includeRepoIntelSource) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "engineering-knowledge-"));
  fs.mkdirSync(path.join(dir, "scripts"), { recursive: true });
  fs.writeFileSync(path.join(dir, "scripts/engineering-knowledge.js"), source);
  if (includeRepoIntelSource) fs.writeFileSync(path.join(dir, "scripts/repository-intelligence.js"), repoIntelSource);
  return dir;
}

function requireFixture(dir) {
  return require(path.join(dir, "scripts/engineering-knowledge.js"));
}

function ok(name) {
  console.log(`${name}: observed expected deterministic outcome`);
}

// 1. loadRepositoryAnalysis fails closed with a clear, actionable message when the file is missing.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  let threw = null;
  try {
    mod.loadRepositoryAnalysis(path.join(dir, "repository-intelligence/repository-analysis.json"));
  } catch (error) {
    threw = error;
  }
  if (!threw || !/not found/.test(threw.message) || !/node scripts\/repository-intelligence\.js/.test(threw.message)) {
    throw new Error(`expected a clear missing-file error naming the fix, got: ${threw && threw.message}`);
  }
  ok("loadRepositoryAnalysis fails closed with an actionable error when repository-analysis.json is missing");
}

// 2. loadRepositoryAnalysis fails closed on invalid JSON.
{
  const dir = makeFixture();
  const file = path.join(dir, "repository-intelligence/repository-analysis.json");
  writeFile(file, "{ not valid json");
  const mod = requireFixture(dir);
  let threw = null;
  try {
    mod.loadRepositoryAnalysis(file);
  } catch (error) {
    threw = error;
  }
  if (!threw || !/not valid JSON/.test(threw.message)) throw new Error(`expected a clear invalid-JSON error, got: ${threw && threw.message}`);
  ok("loadRepositoryAnalysis fails closed on invalid JSON");
}

// 3. loadRepositoryAnalysis successfully parses a valid file.
{
  const dir = makeFixture();
  const file = path.join(dir, "repository-intelligence/repository-analysis.json");
  writeJson(file, ANALYSIS_FIXTURE);
  const mod = requireFixture(dir);
  const analysis = mod.loadRepositoryAnalysis(file);
  if (analysis.projectName !== "Fixture Project") throw new Error("expected the fixture's projectName to round-trip");
  ok("loadRepositoryAnalysis successfully parses a valid repository-analysis.json");
}

// 4. classifyLayer: backend-only, frontend-only, both, and neither.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  if (mod.classifyLayer(["backend/a.js"]) !== "Backend") throw new Error("expected backend-only evidence to classify as Backend");
  if (mod.classifyLayer(["frontend/src/a.js"]) !== "Frontend") throw new Error("expected frontend-only evidence to classify as Frontend");
  if (mod.classifyLayer(["backend/a.js", "frontend/src/a.js"]) !== "Full-stack") throw new Error("expected mixed evidence to classify as Full-stack");
  if (mod.classifyLayer(["docs/a.md"]) !== "Unknown") throw new Error("expected non-backend/frontend evidence to classify as Unknown");
  ok("classifyLayer correctly classifies Backend/Frontend/Full-stack/Unknown");
}

// 5. deriveRelatedDependencies: framework layer-gating (a Backend-only module must not receive frontend-only
//    frameworks), model-file entity extraction, and self-named-model exclusion.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const fullStack = mod.deriveRelatedDependencies("Authentication", "Full-stack", ["backend/models/User.js"], ANALYSIS_FIXTURE.frameworks);
  if (!fullStack.includes("React") || !fullStack.includes("Express") || !fullStack.includes("MongoDB") || !fullStack.includes("Tailwind CSS")) {
    throw new Error(`expected a Full-stack module to receive both frontend and backend frameworks, got: ${fullStack.join(", ")}`);
  }
  if (!fullStack.includes("User")) throw new Error(`expected the User model file to contribute a "User" dependency concept, got: ${fullStack.join(", ")}`);

  const backendOnly = mod.deriveRelatedDependencies("Attendance", "Backend", ["backend/models/Attendance.js"], ANALYSIS_FIXTURE.frameworks);
  if (backendOnly.includes("React") || backendOnly.includes("Tailwind CSS")) {
    throw new Error(`expected a Backend-only module to NOT receive frontend-only frameworks, got: ${backendOnly.join(", ")}`);
  }
  if (!backendOnly.includes("Express") || !backendOnly.includes("MongoDB")) throw new Error(`expected a Backend-only module to receive backend frameworks, got: ${backendOnly.join(", ")}`);
  if (backendOnly.includes("Attendance")) throw new Error(`expected a module's own same-named model file to be excluded from its dependencies, got: ${backendOnly.join(", ")}`);
  ok("deriveRelatedDependencies gates frameworks by layer and excludes a module's own same-named model");
}

// 6. findCoupledModules: overlap detection, self-exclusion, and undetected-module exclusion.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const modules = [
    { name: "A", detected: true, evidence: ["shared.js", "a-only.js"] },
    { name: "B", detected: true, evidence: ["shared.js", "b-only.js"] },
    { name: "C", detected: false, evidence: ["shared.js"] },
  ];
  const coupled = mod.findCoupledModules("A", ["shared.js", "a-only.js"], modules);
  if (JSON.stringify(coupled) !== JSON.stringify(["B"])) throw new Error(`expected A coupled with only B, got: ${JSON.stringify(coupled)}`);
  ok("findCoupledModules detects overlap, excludes self, and excludes undetected modules");
}

// 7. estimateComplexity / estimateArchitecturalImportance bucket thresholds.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  if (mod.estimateComplexity([]) !== "Not applicable") throw new Error("expected empty evidence to yield Not applicable complexity");
  if (mod.estimateComplexity(["a"]) !== "Low") throw new Error("expected 1 file to yield Low complexity");
  if (mod.estimateComplexity(["a", "b", "c", "d"]) !== "Medium") throw new Error("expected 4 files to yield Medium complexity");
  if (mod.estimateComplexity(new Array(8).fill("a")) !== "High") throw new Error("expected 8 files to yield High complexity");

  if (mod.estimateArchitecturalImportance(["frontend/a.js"]) !== "Not applicable") throw new Error("expected zero backend files to yield Not applicable importance");
  if (mod.estimateArchitecturalImportance(["backend/a.js"]) !== "Low") throw new Error("expected 1 backend file to yield Low importance");
  if (mod.estimateArchitecturalImportance(new Array(2).fill("backend/a.js")) !== "Medium") throw new Error("expected 2 backend files to yield Medium importance");
  if (mod.estimateArchitecturalImportance(new Array(5).fill("backend/a.js")) !== "High") throw new Error("expected 5 backend files to yield High importance");
  ok("estimateComplexity and estimateArchitecturalImportance apply the documented bucket thresholds");
}

// 8. estimateCriticality: strong keeps baseline, weak downgrades one level, none is Not applicable, and an
//    unrecognized module name falls back to the Medium baseline.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  if (mod.estimateCriticality("Authentication", "strong") !== "High") throw new Error("expected Authentication+strong to be High");
  if (mod.estimateCriticality("Authentication", "weak") !== "Medium") throw new Error("expected Authentication+weak to downgrade to Medium");
  if (mod.estimateCriticality("Authentication", "none") !== "Not applicable") throw new Error("expected Authentication+none to be Not applicable");
  if (mod.estimateCriticality("SomeUnknownModule", "strong") !== "Medium") throw new Error("expected an unrecognized module name to fall back to the Medium baseline");
  ok("estimateCriticality applies baseline + confidence adjustment correctly, including the unknown-module fallback");
}

// 9. estimateMaintenanceRisk combines confidence, coupling, and technical-debt overlap.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const debt = [{ files: ["backend/x.js"] }];
  if (mod.estimateMaintenanceRisk("none", [], [], debt) !== "Not applicable") throw new Error("expected undetected confidence to yield Not applicable risk");
  if (mod.estimateMaintenanceRisk("strong", [], ["backend/other.js"], debt) !== "Low") throw new Error("expected strong confidence, no coupling, no debt overlap to yield Low risk");
  if (mod.estimateMaintenanceRisk("weak", [], ["backend/other.js"], debt) !== "Medium") throw new Error("expected weak confidence alone to yield Medium risk");
  if (mod.estimateMaintenanceRisk("weak", ["B", "C"], ["backend/x.js"], debt) !== "High") throw new Error("expected weak confidence + coupling + debt overlap to yield High risk");
  ok("estimateMaintenanceRisk combines confidence, coupling, and debt overlap into the documented buckets");
}

// 10. buildKnowledge assembles the full document: a detected Full-stack/strong module, a detected
//     Backend/weak module, and an undetected module with neutral placeholders -- matching the hand-computed
//     expectations for the ANALYSIS_FIXTURE above.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const knowledge = mod.buildKnowledge(ANALYSIS_FIXTURE);
  const byName = Object.fromEntries(knowledge.modules.map((entry) => [entry.name, entry]));

  const auth = byName.Authentication;
  if (auth.layer !== "Full-stack") throw new Error(`expected Authentication layer Full-stack, got ${auth.layer}`);
  if (auth.businessCriticality !== "High") throw new Error(`expected Authentication criticality High, got ${auth.businessCriticality}`);
  if (auth.architecturalImportance !== "Medium") throw new Error(`expected Authentication importance Medium (3 backend files), got ${auth.architecturalImportance}`);
  if (auth.estimatedComplexity !== "Medium") throw new Error(`expected Authentication complexity Medium (4 files), got ${auth.estimatedComplexity}`);
  if (auth.estimatedMaintenanceRisk !== "Medium") throw new Error(`expected Authentication risk Medium (debt overlap on userController.js), got ${auth.estimatedMaintenanceRisk}`);
  if (JSON.stringify(auth.coupledModules) !== "[]") throw new Error(`expected Authentication to share no evidence with Attendance, got ${JSON.stringify(auth.coupledModules)}`);

  const attendance = byName.Attendance;
  if (attendance.layer !== "Backend") throw new Error(`expected Attendance layer Backend, got ${attendance.layer}`);
  if (attendance.businessCriticality !== "Medium") throw new Error(`expected Attendance criticality downgraded to Medium (weak confidence), got ${attendance.businessCriticality}`);
  if (attendance.relatedDependencies.includes("Attendance")) throw new Error("expected Attendance's own same-named model to be excluded from its dependencies");

  const admin = byName.Admin;
  if (admin.detected !== false) throw new Error("expected Admin to be reported as not detected");
  if (admin.layer !== "Not applicable" || admin.businessCriticality !== "Not applicable" || admin.estimatedMaintenanceRisk !== "Not applicable") {
    throw new Error(`expected Admin's derived fields to all be Not applicable, got: ${JSON.stringify(admin)}`);
  }
  if (admin.businessPurpose !== mod.buildKnowledge(ANALYSIS_FIXTURE).modules.find((m) => m.name === "Admin").businessPurpose) {
    throw new Error("expected Admin's curated business purpose to still be present even though undetected");
  }
  ok("buildKnowledge assembles the full document with correct derived fields for detected and undetected modules");
}

// 11. renderMarkdown includes the expected sections for detected modules and the "not detected" note for
//     undetected ones.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const knowledge = mod.buildKnowledge(ANALYSIS_FIXTURE);
  const markdown = mod.renderMarkdown(knowledge);
  for (const heading of ["## Authentication", "## Attendance", "## Admin", "**Purpose:**", "**Criticality:**", "**Layer:**", "**Dependencies:**"]) {
    if (!markdown.includes(heading)) throw new Error(`expected markdown to include "${heading}"`);
  }
  if (!/Admin[\s\S]*Not detected in this repository/.test(markdown)) throw new Error("expected the Admin section to explicitly state it was not detected");
  ok("renderMarkdown includes the expected per-module sections, including the not-detected case");
}

// 12. writeOutputs persists both files, and REPO_INTEL_ANALYSIS_PATH / ENGINEERING_KNOWLEDGE_OUTPUT_DIR
//     override the default input/output locations.
{
  const dir = makeFixture();
  const customInput = path.join(dir, "custom-input/analysis.json");
  writeJson(customInput, ANALYSIS_FIXTURE);
  const previousInput = process.env.REPO_INTEL_ANALYSIS_PATH;
  const previousOutput = process.env.ENGINEERING_KNOWLEDGE_OUTPUT_DIR;
  process.env.REPO_INTEL_ANALYSIS_PATH = "custom-input/analysis.json";
  process.env.ENGINEERING_KNOWLEDGE_OUTPUT_DIR = "custom-output/nested";
  try {
    const mod = requireFixture(dir);
    if (mod.inputPath !== customInput) throw new Error(`expected overridden input path, got: ${mod.inputPath}`);
    if (mod.outputDir !== path.join(dir, "custom-output", "nested")) throw new Error(`expected overridden output directory, got: ${mod.outputDir}`);
    const knowledge = mod.buildKnowledge(mod.loadRepositoryAnalysis(mod.inputPath));
    const { jsonPath, mdPath } = mod.writeOutputs(knowledge);
    if (path.basename(jsonPath) !== "engineering-knowledge.json") throw new Error(`expected output named engineering-knowledge.json, got ${jsonPath}`);
    if (path.basename(mdPath) !== "engineering-knowledge.md") throw new Error(`expected output named engineering-knowledge.md, got ${mdPath}`);
    if (!fs.existsSync(jsonPath) || !fs.existsSync(mdPath)) throw new Error("expected both output files to exist under the overridden output directory");
    JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  } finally {
    if (previousInput === undefined) delete process.env.REPO_INTEL_ANALYSIS_PATH; else process.env.REPO_INTEL_ANALYSIS_PATH = previousInput;
    if (previousOutput === undefined) delete process.env.ENGINEERING_KNOWLEDGE_OUTPUT_DIR; else process.env.ENGINEERING_KNOWLEDGE_OUTPUT_DIR = previousOutput;
  }
  ok("REPO_INTEL_ANALYSIS_PATH and ENGINEERING_KNOWLEDGE_OUTPUT_DIR override the default input/output locations");
}

// 13. CLI fails closed (non-zero exit, clear stderr) when repository-analysis.json does not exist yet.
{
  const dir = makeFixture();
  const result = spawnSync("node", ["scripts/engineering-knowledge.js"], { cwd: dir, encoding: "utf8" });
  if (result.status === 0) throw new Error(`expected the CLI to fail closed with no repository-analysis.json present:\n${result.stdout}`);
  if (!/repository-analysis\.json not found/.test(result.stderr)) throw new Error(`expected a clear missing-input error on stderr, got:\n${result.stderr}`);
  ok("CLI fails closed with a clear error when repository-analysis.json has not been generated yet");
}

// 14. True end-to-end: running Repository Intelligence's own CLI followed by this engine's CLI (the real
//     documented single-command chain, using the real repository-intelligence.js source, not a fixture)
//     produces valid engineering-knowledge.json and .md.
{
  const dir = makeFixture(true);
  const repoIntelRun = spawnSync("node", ["scripts/repository-intelligence.js"], { cwd: dir, encoding: "utf8" });
  if (repoIntelRun.status !== 0) throw new Error(`Repository Intelligence run failed:\n${repoIntelRun.stdout}\n${repoIntelRun.stderr}`);
  const run = spawnSync("node", ["scripts/engineering-knowledge.js"], { cwd: dir, encoding: "utf8" });
  if (run.status !== 0) throw new Error(`Engineering Knowledge run failed:\n${run.stdout}\n${run.stderr}`);
  const jsonPath = path.join(dir, "engineering-knowledge", "engineering-knowledge.json");
  const mdPath = path.join(dir, "engineering-knowledge", "engineering-knowledge.md");
  if (!fs.existsSync(jsonPath)) throw new Error("expected engineering-knowledge.json to be produced by the real end-to-end chain");
  if (!fs.existsSync(mdPath)) throw new Error("expected engineering-knowledge.md to be produced by the real end-to-end chain");
  const knowledge = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  if (!Array.isArray(knowledge.modules) || !knowledge.modules.length) throw new Error("expected the real end-to-end run to produce a non-empty modules array");
  ok("the real single-command chain (repository-intelligence.js -> engineering-knowledge.js) produces valid output");
}

console.log("All Engineering Knowledge Engine v1 regression scenarios passed.");
