#!/usr/bin/env node
// Recommendation Engine v1 regression coverage: every deterministic derivation produces the expected,
// reproducible result against a hand-crafted engineering-knowledge.json fixture (this engine's only
// contract is that JSON shape, so tests are decoupled from Engineering Knowledge's own internals), plus
// one true end-to-end run proving the real three-stage chain (Repository Intelligence -> Engineering
// Knowledge -> Recommendation Engine) actually works together.
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");

const repoRoot = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(repoRoot, "scripts/recommendation-engine.js"), "utf8");
const repoIntelSource = fs.readFileSync(path.join(repoRoot, "scripts/repository-intelligence.js"), "utf8");
const engKnowledgeSource = fs.readFileSync(path.join(repoRoot, "scripts/engineering-knowledge.js"), "utf8");

function writeFile(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function writeJson(file, value) {
  writeFile(file, `${JSON.stringify(value, null, 2)}\n`);
}

// A precisely hand-crafted engineering-knowledge.json -- not generated by Engineering Knowledge -- covering
// every rule's positive AND a nearby negative case, a genuine multi-module file-intersection for the
// coupling rule, and one module that legitimately triggers no rule at all.
const KNOWLEDGE_FIXTURE = {
  sourceProjectName: "Fixture Project",
  sourceTimestamp: "2026-01-01T00:00:00.000Z",
  modules: [
    {
      name: "Authentication",
      detected: true,
      detectionConfidence: "strong",
      businessPurpose: "Verifies identity.",
      layer: "Full-stack",
      relatedFiles: ["backend/routes/authRoutes.js", "backend/models/User.js", "backend/routes/attendanceRoutes.js"],
      relatedDependencies: ["Express", "MongoDB"],
      coupledModules: ["Attendance", "Reports"],
      businessCriticality: "High",
      architecturalImportance: "High",
      estimatedComplexity: "High",
      estimatedMaintenanceRisk: "Medium",
    },
    {
      name: "Attendance",
      detected: true,
      detectionConfidence: "weak",
      businessPurpose: "Tracks attendance.",
      layer: "Backend",
      relatedFiles: ["backend/models/Attendance.js", "backend/routes/attendanceRoutes.js"],
      relatedDependencies: ["Express"],
      coupledModules: ["Authentication"],
      businessCriticality: "Low",
      architecturalImportance: "Medium",
      estimatedComplexity: "Low",
      estimatedMaintenanceRisk: "High",
    },
    {
      name: "Reports",
      detected: true,
      detectionConfidence: "weak",
      businessPurpose: "Reports on performance.",
      layer: "Backend",
      relatedFiles: ["backend/controllers/reportsController.js"],
      relatedDependencies: [],
      coupledModules: [],
      businessCriticality: "Medium",
      architecturalImportance: "Low",
      estimatedComplexity: "Medium",
      estimatedMaintenanceRisk: "Low",
    },
    {
      name: "Faculty",
      detected: true,
      detectionConfidence: "strong",
      businessPurpose: "Supports faculty.",
      layer: "Not applicable",
      relatedFiles: [],
      relatedDependencies: [],
      coupledModules: [],
      businessCriticality: "Low",
      architecturalImportance: "Low",
      estimatedComplexity: "Low",
      estimatedMaintenanceRisk: "Low",
    },
    {
      name: "Admin",
      detected: false,
      detectionConfidence: "none",
      businessPurpose: "Not curated.",
      layer: "Not applicable",
      relatedFiles: [],
      relatedDependencies: [],
      coupledModules: [],
      businessCriticality: "Not applicable",
      architecturalImportance: "Not applicable",
      estimatedComplexity: "Not applicable",
      estimatedMaintenanceRisk: "Not applicable",
    },
  ],
};

function makeFixture(includeUpstreamSources) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "recommendation-engine-"));
  fs.mkdirSync(path.join(dir, "scripts"), { recursive: true });
  fs.writeFileSync(path.join(dir, "scripts/recommendation-engine.js"), source);
  if (includeUpstreamSources) {
    fs.writeFileSync(path.join(dir, "scripts/repository-intelligence.js"), repoIntelSource);
    fs.writeFileSync(path.join(dir, "scripts/engineering-knowledge.js"), engKnowledgeSource);
  }
  return dir;
}

function requireFixture(dir) {
  return require(path.join(dir, "scripts/recommendation-engine.js"));
}

function ok(name) {
  console.log(`${name}: observed expected deterministic outcome`);
}

// 1. loadEngineeringKnowledge fails closed with a clear, actionable message when the file is missing.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  let threw = null;
  try {
    mod.loadEngineeringKnowledge(path.join(dir, "engineering-knowledge/engineering-knowledge.json"));
  } catch (error) {
    threw = error;
  }
  if (!threw || !/not found/.test(threw.message) || !/node scripts\/engineering-knowledge\.js/.test(threw.message)) {
    throw new Error(`expected a clear missing-file error naming the fix, got: ${threw && threw.message}`);
  }
  ok("loadEngineeringKnowledge fails closed with an actionable error when engineering-knowledge.json is missing");
}

// 2. loadEngineeringKnowledge fails closed on invalid JSON.
{
  const dir = makeFixture();
  const file = path.join(dir, "engineering-knowledge/engineering-knowledge.json");
  writeFile(file, "{ not valid json");
  const mod = requireFixture(dir);
  let threw = null;
  try {
    mod.loadEngineeringKnowledge(file);
  } catch (error) {
    threw = error;
  }
  if (!threw || !/not valid JSON/.test(threw.message)) throw new Error(`expected a clear invalid-JSON error, got: ${threw && threw.message}`);
  ok("loadEngineeringKnowledge fails closed on invalid JSON");
}

// 3. loadEngineeringKnowledge successfully parses a valid file.
{
  const dir = makeFixture();
  const file = path.join(dir, "engineering-knowledge/engineering-knowledge.json");
  writeJson(file, KNOWLEDGE_FIXTURE);
  const mod = requireFixture(dir);
  const knowledge = mod.loadEngineeringKnowledge(file);
  if (knowledge.sourceProjectName !== "Fixture Project") throw new Error("expected the fixture's sourceProjectName to round-trip");
  ok("loadEngineeringKnowledge successfully parses a valid engineering-knowledge.json");
}

// 4. computeModuleScore applies the documented weighted formula exactly.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const auth = KNOWLEDGE_FIXTURE.modules[0]; // High/High/Medium/High, coupling 2 -> raw 29 -> 88
  if (mod.computeModuleScore(auth) !== 88) throw new Error(`expected Authentication's score to be 88, got ${mod.computeModuleScore(auth)}`);
  const attendance = KNOWLEDGE_FIXTURE.modules[1]; // Low/Medium/High/Low, coupling 1 -> raw 19 -> 58
  if (mod.computeModuleScore(attendance) !== 58) throw new Error(`expected Attendance's score to be 58, got ${mod.computeModuleScore(attendance)}`);
  const reports = KNOWLEDGE_FIXTURE.modules[2]; // Medium/Low/Low/Medium, coupling 0 -> raw 15 -> 45
  if (mod.computeModuleScore(reports) !== 45) throw new Error(`expected Reports's score to be 45, got ${mod.computeModuleScore(reports)}`);
  const admin = KNOWLEDGE_FIXTURE.modules[4]; // all Not applicable -> raw 0 -> 0
  if (mod.computeModuleScore(admin) !== 0) throw new Error(`expected Admin's (Not applicable) score to be 0, got ${mod.computeModuleScore(admin)}`);
  ok("computeModuleScore applies the documented weighted formula exactly");
}

// 5. computeConfidence: base per detectionConfidence, +8 per reason, capped at 100, and an unrecognized
//    confidence level falls back to the same base as "weak".
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  if (mod.computeConfidence("strong", 3) !== 94) throw new Error(`expected strong+3 reasons to be 94, got ${mod.computeConfidence("strong", 3)}`);
  if (mod.computeConfidence("weak", 2) !== 66) throw new Error(`expected weak+2 reasons to be 66, got ${mod.computeConfidence("weak", 2)}`);
  if (mod.computeConfidence("strong", 10) !== 100) throw new Error(`expected confidence to cap at 100, got ${mod.computeConfidence("strong", 10)}`);
  if (mod.computeConfidence("unknown", 0) !== 50) throw new Error(`expected an unrecognized confidence level to fall back to base 50, got ${mod.computeConfidence("unknown", 0)}`);
  ok("computeConfidence applies base + per-reason increments correctly, capped at 100");
}

// 6. estimateImpact boundary behavior.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  if (mod.estimateImpact("High", "High") !== "High") throw new Error("expected High+High to be High impact");
  if (mod.estimateImpact("High", "Medium") !== "High") throw new Error("expected High+Medium (weight 5) to be High impact");
  if (mod.estimateImpact("Medium", "Medium") !== "Medium") throw new Error("expected Medium+Medium (weight 4) to be Medium impact");
  if (mod.estimateImpact("Low", "Low") !== "Low") throw new Error("expected Low+Low to be Low impact");
  if (mod.estimateImpact("Not applicable", "Not applicable") !== "Low") throw new Error("expected Not applicable+Not applicable to be Low impact");
  ok("estimateImpact applies the documented weight-sum boundaries correctly");
}

// 7-11: generateRecommendations produces exactly the expected triggered rules, with correctly-derived
//       reason/size/risk/affectedFiles per rule, and skips undetected modules and modules with no
//       triggered rule entirely.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const recs = mod.generateRecommendations(KNOWLEDGE_FIXTURE);
  const byRule = (moduleName, ruleKey) => recs.find((rec) => rec.affectedModules[0] === moduleName && rec.ruleKey === ruleKey);

  // 7. extract-complex-logic: triggers for Authentication (High complexity + Medium risk), not for
  //    Attendance (Low complexity) or Reports (Medium complexity, not High).
  const authExtract = byRule("Authentication", "extract-complex-logic");
  if (!authExtract) throw new Error("expected extract-complex-logic to trigger for Authentication");
  if (authExtract.estimatedRisk !== "Low") throw new Error(`expected Medium module risk to map to Low implementation risk, got ${authExtract.estimatedRisk}`);
  if (authExtract.estimatedImplementationSize !== "Small") throw new Error(`expected extract-complex-logic size Small, got ${authExtract.estimatedImplementationSize}`);
  if (JSON.stringify(authExtract.reason) !== JSON.stringify(["Authentication has High complexity", "Medium maintenance risk", "Touches 3 related file(s)"])) {
    throw new Error(`unexpected reason array: ${JSON.stringify(authExtract.reason)}`);
  }
  if (byRule("Attendance", "extract-complex-logic") || byRule("Reports", "extract-complex-logic")) {
    throw new Error("expected extract-complex-logic to NOT trigger for Attendance or Reports (complexity not High)");
  }

  // 8. reduce-coupling: triggers for Authentication (High importance + 2 coupled modules), with
  //    affectedFiles being the true file-level intersection with Attendance only (Reports shares nothing).
  const authCoupling = byRule("Authentication", "reduce-coupling");
  if (!authCoupling) throw new Error("expected reduce-coupling to trigger for Authentication");
  if (JSON.stringify(authCoupling.affectedFiles) !== JSON.stringify(["backend/routes/attendanceRoutes.js"])) {
    throw new Error(`expected reduce-coupling affectedFiles to be exactly the true file intersection, got: ${JSON.stringify(authCoupling.affectedFiles)}`);
  }
  if (JSON.stringify(authCoupling.affectedModules) !== JSON.stringify(["Authentication", "Attendance", "Reports"])) {
    throw new Error(`expected reduce-coupling affectedModules to include the module plus its coupled modules, got: ${JSON.stringify(authCoupling.affectedModules)}`);
  }
  if (byRule("Attendance", "reduce-coupling") || byRule("Reports", "reduce-coupling")) {
    throw new Error("expected reduce-coupling to NOT trigger for Attendance (Medium importance) or Reports (0 coupled modules)");
  }

  // 9. address-maintenance-risk: triggers only for Attendance (High risk).
  if (!byRule("Attendance", "address-maintenance-risk")) throw new Error("expected address-maintenance-risk to trigger for Attendance");
  if (byRule("Authentication", "address-maintenance-risk") || byRule("Reports", "address-maintenance-risk")) {
    throw new Error("expected address-maintenance-risk to NOT trigger for Authentication (Medium risk) or Reports (Low risk)");
  }

  // 10. strengthen-detection-coverage: triggers for Reports (weak + Medium criticality), NOT for Attendance
  //     (weak but Low criticality -- the negative case for the criticality gate).
  if (!byRule("Reports", "strengthen-detection-coverage")) throw new Error("expected strengthen-detection-coverage to trigger for Reports");
  if (byRule("Attendance", "strengthen-detection-coverage")) {
    throw new Error("expected strengthen-detection-coverage to NOT trigger for Attendance (weak confidence but Low criticality)");
  }

  // 11. Faculty (all-Low, strong confidence) triggers nothing; Admin (undetected) is skipped entirely
  //     regardless of any field values.
  if (recs.some((rec) => rec.affectedModules.includes("Faculty"))) throw new Error("expected Faculty to trigger no recommendations at all");
  if (recs.some((rec) => rec.affectedModules.includes("Admin"))) throw new Error("expected undetected Admin to be skipped entirely");

  ok("generateRecommendations triggers exactly the expected rules with correctly-derived fields, including all documented negative cases");
}

// 12. buildRecommendationsReport sorts by descending priority (confidence as tiebreak), preserves stable
//     ids independent of the sort, and includes the documented metadata fields.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const report = mod.buildRecommendationsReport(KNOWLEDGE_FIXTURE);
  for (const key of ["generatedFrom", "sourceProjectName", "sourceTimestamp", "scoringFormula", "recommendations", "timestamp"]) {
    if (!(key in report)) throw new Error(`report is missing required field: ${key}`);
  }
  const scores = report.recommendations.map((rec) => rec.priorityScore);
  const sortedDescending = [...scores].sort((a, b) => b - a);
  if (JSON.stringify(scores) !== JSON.stringify(sortedDescending)) throw new Error(`expected recommendations sorted by descending priorityScore, got: ${JSON.stringify(scores)}`);
  // Authentication's two recommendations share priorityScore 88; among ties, higher confidence must sort first.
  const authRecs = report.recommendations.filter((rec) => rec.affectedModules[0] === "Authentication");
  if (authRecs.length === 2 && authRecs[0].confidence < authRecs[1].confidence) {
    throw new Error(`expected the tied-priority Authentication recommendations to be ordered by descending confidence, got: ${JSON.stringify(authRecs.map((r) => r.confidence))}`);
  }
  const ids = report.recommendations.map((rec) => rec.id);
  if (new Set(ids).size !== ids.length) throw new Error("expected every recommendation id to be unique");
  ok("buildRecommendationsReport sorts by descending priority with a confidence tiebreak and includes all documented metadata");
}

// 13. renderMarkdown includes the expected sections, and reports the empty-recommendations case honestly.
{
  const dir = makeFixture();
  const mod = requireFixture(dir);
  const report = mod.buildRecommendationsReport(KNOWLEDGE_FIXTURE);
  const markdown = mod.renderMarkdown(report);
  for (const heading of ["# Engineering Recommendations Report", "## Scoring formula", "## Recommendations", "**Priority score:**", "**Reason:**", "**Affected files:**"]) {
    if (!markdown.includes(heading)) throw new Error(`expected markdown to include "${heading}"`);
  }

  const emptyKnowledge = { ...KNOWLEDGE_FIXTURE, modules: [KNOWLEDGE_FIXTURE.modules[3]] }; // only Faculty (triggers nothing)
  const emptyReport = mod.buildRecommendationsReport(emptyKnowledge);
  if (emptyReport.recommendations.length !== 0) throw new Error("expected a module that triggers nothing to produce zero recommendations");
  const emptyMarkdown = mod.renderMarkdown(emptyReport);
  if (!/No recommendations were triggered/.test(emptyMarkdown)) throw new Error("expected the empty case to be reported honestly in markdown, not silently omitted");
  ok("renderMarkdown includes the expected sections and honestly reports the empty-recommendations case");
}

// 14. writeOutputs persists both files, and ENGINEERING_KNOWLEDGE_PATH / RECOMMENDATIONS_OUTPUT_DIR
//     override the default input/output locations.
{
  const dir = makeFixture();
  const customInput = path.join(dir, "custom-input/knowledge.json");
  writeJson(customInput, KNOWLEDGE_FIXTURE);
  const previousInput = process.env.ENGINEERING_KNOWLEDGE_PATH;
  const previousOutput = process.env.RECOMMENDATIONS_OUTPUT_DIR;
  process.env.ENGINEERING_KNOWLEDGE_PATH = "custom-input/knowledge.json";
  process.env.RECOMMENDATIONS_OUTPUT_DIR = "custom-output/nested";
  try {
    const mod = requireFixture(dir);
    if (mod.inputPath !== customInput) throw new Error(`expected overridden input path, got: ${mod.inputPath}`);
    if (mod.outputDir !== path.join(dir, "custom-output", "nested")) throw new Error(`expected overridden output directory, got: ${mod.outputDir}`);
    const report = mod.buildRecommendationsReport(mod.loadEngineeringKnowledge(mod.inputPath));
    const { jsonPath, mdPath } = mod.writeOutputs(report);
    if (path.basename(jsonPath) !== "recommendations.json") throw new Error(`expected output named recommendations.json, got ${jsonPath}`);
    if (path.basename(mdPath) !== "recommendations.md") throw new Error(`expected output named recommendations.md, got ${mdPath}`);
    if (!fs.existsSync(jsonPath) || !fs.existsSync(mdPath)) throw new Error("expected both output files to exist under the overridden output directory");
    JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  } finally {
    if (previousInput === undefined) delete process.env.ENGINEERING_KNOWLEDGE_PATH; else process.env.ENGINEERING_KNOWLEDGE_PATH = previousInput;
    if (previousOutput === undefined) delete process.env.RECOMMENDATIONS_OUTPUT_DIR; else process.env.RECOMMENDATIONS_OUTPUT_DIR = previousOutput;
  }
  ok("ENGINEERING_KNOWLEDGE_PATH and RECOMMENDATIONS_OUTPUT_DIR override the default input/output locations");
}

// 15. CLI fails closed (non-zero exit, clear stderr) when engineering-knowledge.json does not exist yet.
{
  const dir = makeFixture();
  const result = spawnSync("node", ["scripts/recommendation-engine.js"], { cwd: dir, encoding: "utf8" });
  if (result.status === 0) throw new Error(`expected the CLI to fail closed with no engineering-knowledge.json present:\n${result.stdout}`);
  if (!/engineering-knowledge\.json not found/.test(result.stderr)) throw new Error(`expected a clear missing-input error on stderr, got:\n${result.stderr}`);
  ok("CLI fails closed with a clear error when engineering-knowledge.json has not been generated yet");
}

// 16. True end-to-end: the real three-stage chain (repository-intelligence.js -> engineering-knowledge.js
//     -> recommendation-engine.js), using the real upstream sources, produces valid recommendations output.
{
  const dir = makeFixture(true);
  const repoIntelRun = spawnSync("node", ["scripts/repository-intelligence.js"], { cwd: dir, encoding: "utf8" });
  if (repoIntelRun.status !== 0) throw new Error(`Repository Intelligence run failed:\n${repoIntelRun.stdout}\n${repoIntelRun.stderr}`);
  const knowledgeRun = spawnSync("node", ["scripts/engineering-knowledge.js"], { cwd: dir, encoding: "utf8" });
  if (knowledgeRun.status !== 0) throw new Error(`Engineering Knowledge run failed:\n${knowledgeRun.stdout}\n${knowledgeRun.stderr}`);
  const run = spawnSync("node", ["scripts/recommendation-engine.js"], { cwd: dir, encoding: "utf8" });
  if (run.status !== 0) throw new Error(`Recommendation Engine run failed:\n${run.stdout}\n${run.stderr}`);
  const jsonPath = path.join(dir, "recommendations", "recommendations.json");
  const mdPath = path.join(dir, "recommendations", "recommendations.md");
  if (!fs.existsSync(jsonPath)) throw new Error("expected recommendations.json to be produced by the real end-to-end chain");
  if (!fs.existsSync(mdPath)) throw new Error("expected recommendations.md to be produced by the real end-to-end chain");
  const report = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  if (!Array.isArray(report.recommendations)) throw new Error("expected the real end-to-end run to produce a recommendations array");
  ok("the real three-stage chain (repository-intelligence.js -> engineering-knowledge.js -> recommendation-engine.js) produces valid output");
}

console.log("All Recommendation Engine v1 regression scenarios passed.");
